# use a docker image with glibc 2.28 in it for testing
docker_image:                               # [linux64]
- quay.io/condaforge/linux-anvil-alma:8     # [linux64]

dnnl_cpu_runtime:
  - tbb  # [not (ppc64le or aarch64)]
  - omp
  - threadpool # [not (ppc64le or aarch64 or arm64)]
  - dpcpp # [x86_64 and (linux64 or win64)]
