# use a docker image with glibc 2.28 in it for testing
docker_image:                                  # [x86_64 and linux64]
- quay.io/condaforge/linux-anvil-alma-x86_64:8 # [x86_64 and linux64]

dnnl_cpu_runtime:
  - tbb  # [not (ppc64le or aarch64)]
  - omp
  - threadpool # [not (ppc64le or aarch64 or arm64)]
  - dpcpp # [x86_64 and linux64]
