{% set name = "oneDNN" %}
{% set version = "3.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/oneapi-src/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d150a77025f38bff182aaef4dd643625563b2f311c635f86cf4b769b04d7b48
  patches:
    - 0001-Add-TBB-tbb-to-TBB_IMPORTED_TARGETS.patch

build:
  number: 3

outputs:
  - name: {{ name|lower }}
    script: build-onednn.sh  # [not win]
    script: bld-onednn.bat  # [win]
    version: {{ version }}
    build:
      string: {{ dnnl_cpu_runtime }}_{{ dnnl_gpu_runtime }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage("onednn", max_pin="x") }}
      track_features:
      {% if dnnl_cpu_runtime != "omp" %}
        - onednn-{{ dnnl_cpu_runtime }}
      {% endif %}
      {% if dnnl_gpu_runtime != "none" %}
        - onednn-{{ dnnl_gpu_runtime }}
      {% endif %}
      requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('dpcpp') }}  # [dnnl_cpu_runtime == "dpcpp" or dnnl_gpu_runtime == "dpcpp"]
        - llvm-openmp  # [osx]
      host:
        - tbb        # [dnnl_cpu_runtime == "tbb" or dnnl_cpu_runtime == "dpcpp"]
        - tbb-devel  # [dnnl_cpu_runtime == "tbb" or dnnl_cpu_runtime == "dpcpp"]
    about:
      home: https://github.com/oneapi-src/oneDNN
      license: Apache-2.0
      license_file:
        - THIRD-PARTY-PROGRAMS
        - LICENSE
      summary: oneAPI Deep Neural Network Library (oneDNN)
      description: |
          oneAPI Deep Neural Network Library (oneDNN) is an open-source
          cross-platform performance library of basic building blocks for deep
          learning applications.

          oneDNN is intended for deep learning applications and framework
          developers interested in improving application performance.
          Deep learning practitioners should use one of the applications
          enabled with oneDNN.

      {% if dnnl_cpu_runtime == "omp" %}
          In this package oneDNN is built with the OpenMP CPU runtime.
      {% elif dnnl_cpu_runtime == "tbb" %}
          In this package oneDNN is built with the TBB CPU runtime.
      {% elif dnnl_cpu_runtime == "threadpool" %}
          In this package oneDNN is built with the Threadpool CPU runtime.
          oneDNN requires the user to implement a Threadpool interface to enable
          the library to perform computations using multiple threads.
      {% endif %}

          For more information please read oneDNN developer guide:
          https://oneapi-src.github.io/oneDNN/
    test:
      commands:
        - test -f ${PREFIX}/lib/libdnnl${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/include/oneapi/dnnl/dnnl.h  # [unix]
        - if not exist %LIBRARY_PREFIX%\\bin\\dnnl.dll exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\lib\\dnnl.lib exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\include\\dnnl.h exit 1  # [win]

  - name: onednn-cpu-{{ dnnl_cpu_runtime }}-gpu-{{ dnnl_gpu_runtime }}
    version: {{ version }}
    build:
      string: {{ dnnl_cpu_runtime }}_{{ dnnl_gpu_runtime }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage("onednn", max_pin="x") }}
    requirements:
      host:
        - {{ pin_subpackage('onednn', exact=True) }}
      run:
        - {{ pin_subpackage('onednn', exact=True) }}
    about:
      home: https://github.com/oneapi-src/oneDNN
      license: Apache-2.0
      license_file: LICENSE
      summary: oneAPI Deep Neural Network Library (oneDNN)
      description: |
          oneAPI Deep Neural Network Library (oneDNN) is an open-source
          cross-platform performance library of basic building blocks for deep
          learning applications.

          oneDNN is intended for deep learning applications and framework
          developers interested in improving application performance.
          Deep learning practitioners should use one of the applications
          enabled with oneDNN.

      {% if dnnl_cpu_runtime == "omp" %}
          In this package oneDNN is built with the OpenMP CPU runtime.
      {% elif dnnl_cpu_runtime == "tbb" %}
          In this package oneDNN is built with the TBB CPU runtime.
      {% elif dnnl_cpu_runtime == "threadpool" %}
          In this package oneDNN is built with the Threadpool CPU runtime.
          oneDNN requires the user to implement a Threadpool interface to enable
          the library to perform computations using multiple threads.
      {% endif %}

          For more information please read oneDNN developer guide:
          https://oneapi-src.github.io/oneDNN/
    test:
      commands:
        - exit 0

  - name: onednn-gpu-{{ dnnl_gpu_runtime }}
    version: {{ version }}
    build:
      string: {{ dnnl_cpu_runtime }}_{{ dnnl_gpu_runtime }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage("onednn", max_pin="x") }}
      track_features:
      {% if dnnl_gpu_runtime != "none" %}
        - onednn-{{ dnnl_gpu_runtime }}
      {% endif %}
    requirements:
      host:
        - {{ pin_subpackage('onednn', exact=True) }}
      run:
        - {{ pin_subpackage('onednn', exact=True) }}
        - onednn-cpu-{{ dnnl_cpu_runtime }}-gpu-{{ dnnl_gpu_runtime }}
    about:
      home: https://github.com/oneapi-src/oneDNN
      license: Apache-2.0
      license_file: LICENSE
      summary: oneAPI Deep Neural Network Library (oneDNN)
    test:
      commands:
        - exit 0

  - name: onednn-cpu-{{ dnnl_cpu_runtime }}
    version: {{ version }}
    build:
      string: {{ dnnl_cpu_runtime }}_{{ dnnl_gpu_runtime }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage("onednn", max_pin="x") }}
      track_features:
      {% if dnnl_cpu_runtime != "omp" %}
        - onednn-{{ dnnl_cpu_runtime }}
      {% endif %}
    requirements:
      host:
        - {{ pin_subpackage('onednn', exact=True) }}
      run:
        - {{ pin_subpackage('onednn', exact=True) }}
        - onednn-cpu-{{ dnnl_cpu_runtime }}-gpu-{{ dnnl_gpu_runtime }}
    about:
      home: https://github.com/oneapi-src/oneDNN
      license: Apache-2.0
      license_file: LICENSE
      summary: oneAPI Deep Neural Network Library (oneDNN)
    test:
      commands:
        - exit 0

about:
  home: https://github.com/oneapi-src/oneDNN
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRD-PARTY-PROGRAMS
  summary: oneAPI Deep Neural Network Library (oneDNN)

extra:
  feedstock-name: {{ name|lower }}
  recipe-maintainers:
    - xhochy
    - igorsafo
